insert into public.products (slug, title, description, price_minor, category, cover_path, file_path, file_name) values
('minimalist-resume-template', 'Minimalist Resume Template', 'A clean one-page resume layout with a sidebar for contact details and skills. Print-ready PDF with clear placeholders.', 900, 'Templates', '/covers/minimalist-resume-template.svg', 'minimalist-resume-template.pdf', 'minimalist-resume-template.pdf'),
('monthly-budget-planner', 'Monthly Budget Planner', 'Plan income, fixed and variable expenses and savings goals on a single printable page.', 700, 'Templates', '/covers/monthly-budget-planner.svg', 'monthly-budget-planner.pdf', 'monthly-budget-planner.pdf'),
('habit-tracker-printable', 'Habit Tracker Printable', 'A landscape monthly grid for tracking up to twelve habits across thirty-one days.', 500, 'Templates', '/covers/habit-tracker-printable.svg', 'habit-tracker-printable.pdf', 'habit-tracker-printable.pdf'),
('study-planner-bundle', 'Study Planner Bundle', 'A weekly timetable plus an exam and assignment tracker to keep coursework on schedule.', 800, 'Templates', '/covers/study-planner-bundle.svg', 'study-planner-bundle.pdf', 'study-planner-bundle.pdf'),
('thirty-minute-meals-cookbook', '30-Minute Meals Cookbook', 'Five simple dinners that are ready in half an hour, with ingredient lists and clear steps.', 1200, 'Books', '/covers/thirty-minute-meals-cookbook.svg', 'thirty-minute-meals-cookbook.pdf', 'thirty-minute-meals-cookbook.pdf'),
('abstract-gradient-wallpapers', 'Abstract Gradient Wallpapers', 'Five soft gradient phone wallpapers in 1080 by 1920 resolution.', 600, 'Wallpapers', '/covers/abstract-gradient-wallpapers.svg', 'abstract-gradient-wallpapers.zip', 'abstract-gradient-wallpapers.zip'),
('minimal-nature-wallpapers', 'Minimal Nature Wallpapers', 'Five layered mountain and sunrise phone wallpapers in calm colour palettes.', 600, 'Wallpapers', '/covers/minimal-nature-wallpapers.svg', 'minimal-nature-wallpapers.zip', 'minimal-nature-wallpapers.zip'),
('social-media-post-kit', 'Social Media Post Kit', 'Six square post templates for quotes, announcements, tips and sales, ready to customise.', 1000, 'Templates', '/covers/social-media-post-kit.svg', 'social-media-post-kit.zip', 'social-media-post-kit.zip')
on conflict (slug) do nothing;
